# User
- name: Create dixans user
  user: name=dixans

# Git package + repo
- name: Install git package
  apt: pkg=git state=present

- name: Create repo directory
  file: path=/srv/dixans state=directory owner=dixans group=dixans mode=0775

- name: Pull repo
  git: repo=https://github.com/pmourlanne/dixans.git dest=/srv/dixans
  become: true
  become_user: dixans

# Venv
- name: Install python-virtualenv
  apt: pkg=python-virtualenv state=present update_cache=yes

- name: Install requirements in venv
  pip:
    requirements: /srv/dixans/requirements.txt
    virtualenv: /srv/dixans/venv
    virtualenv_python: python3
  become_user: dixans

# Supervisor
- name: Install supervisor package
  apt: pkg=supervisor state=present update_cache=yes

- name: Make sure the log directory exists
  file:
    path=/var/log/dixans
    owner=dixans
    group=dixans
    state=directory

- name: Copy supervisor conf
  template: src=supervisor.conf dest=/etc/supervisor/conf.d/dixans.conf

- name: Supervisor reread
  command: /usr/bin/supervisorctl reread

- name: Supervisor update
  command: /usr/bin/supervisorctl update

- supervisorctl: name=dixans_wsgi state=restarted

# Nginx
- name: Install nginx packags
  apt: pkg=nginx state=present update_cache=yes

- name: Copy nginx conf
  # Template needs to be before `ctp_reverse_proxy.conf`, don't ask too many questions`
  template: src=nginx.conf dest=/etc/nginx/sites-enabled/aaadixans
  notify: restart nginx
